### ISSUE TITLE
Example package json invalid?

### ISSUE THREAD

**Issue by JuanCaicedo** [rnons/elm-svg-loader#1]
Hi there! I followed these steps

```
https://github.com/rnons/elm-svg-loader.git
cd elm-svg-loader/examples
npm install
npm start
```
And get this error
![image](https://user-images.githubusercontent.com/4341496/33990535-e693555e-e0fd-11e7-9d74-080d6b05e929.png)

It goes away if I change the version to `1.0.0`

**Comment by rnons** [comment]
closed by #6
