### ISSUE TITLE
Can't find loader utils

### ISSUE THREAD

**Issue by JuanCaicedo** [rnons/elm-svg-loader#3]
I get this error when trying to run the example 
![image](https://user-images.githubusercontent.com/4341496/33990787-b0408afc-e0fe-11e7-933a-2253ca68dd1d.png)
I think you can repro this following these steps (after fixing #1)
```
git clone https://github.com/rnons/elm-svg-loader.git
cd elm-svg-loader/examples
npm install
npm start
```

**Comment by rnons** [comment]
closed by #6
